class SymptomService {
  const SymptomService();

  /// Suggests the most relevant doctor specialization.
  ///
  /// This is for doctor discovery only.
  /// It is NOT a medical diagnosis.
  String suggestSpecialization(List<String> symptoms) {
    final text = _normalize(symptoms.join(' '));

    if (text.isEmpty) {
      return 'General Physician';
    }

    final scores = <String, int>{};

    // First score the detailed phrases already stored in the
    // symptom database.
    for (final entry in symptomKeywords.entries) {
      final score = _calculateScore(text, entry.value);

      if (score > 0) {
        scores[entry.key] = score;
      }
    }

    // Then score bulk single-word aliases such as:
    // teeth -> Dentist
    // fever -> General Physician
    // headache -> Neurologist
    final tokens = text.split(' ').where((word) => word.isNotEmpty).toSet();

    final wordMatches = _singleWordMatches(tokens);

    for (final entry in wordMatches.entries) {
      scores[entry.key] = (scores[entry.key] ?? 0) + entry.value;
    }

    if (scores.isEmpty) {
      return 'General Physician';
    }

    String bestSpecialization = 'General Physician';
    int bestScore = 0;

    for (final entry in scores.entries) {
      if (entry.value > bestScore) {
        bestScore = entry.value;
        bestSpecialization = entry.key;
      }
    }

    return bestSpecialization;
  }

  /// Returns all specializations matching the entered symptoms.
  ///
  /// The first item is the strongest match.
  List<String> matchingSpecializations(List<String> symptoms) {
    final text = _normalize(symptoms.join(' '));

    if (text.isEmpty) {
      return ['General Physician'];
    }

    final scores = <String, int>{};

    for (final entry in symptomKeywords.entries) {
      final score = _calculateScore(text, entry.value);

      if (score > 0) {
        scores[entry.key] = score;
      }
    }

    final tokens = text.split(' ').where((word) => word.isNotEmpty).toSet();

    final wordMatches = _singleWordMatches(tokens);

    for (final entry in wordMatches.entries) {
      scores[entry.key] = (scores[entry.key] ?? 0) + entry.value;
    }

    if (scores.isEmpty) {
      return ['General Physician'];
    }

    final result = scores.keys.toList();

    result.sort(
      (a, b) => scores[b]!.compareTo(scores[a]!),
    );

    return result;
  }

  /// Returns the matching keywords found in the patient's text.
  List<String> matchedSymptoms(List<String> symptoms) {
    final text = _normalize(symptoms.join(' '));

    if (text.isEmpty) {
      return [];
    }

    final matches = <String>[];

    for (final keywords in symptomKeywords.values) {
      for (final keyword in keywords) {
        if (_containsKeyword(text, keyword)) {
          matches.add(keyword);
        }
      }
    }

    final tokens = text.split(' ').where((word) => word.isNotEmpty).toSet();

    for (final token in tokens) {
      if (_wordAliases.containsKey(token)) {
        matches.add(token);
      }
    }

    return matches.toSet().toList();
  }

  int _calculateScore(
    String text,
    List<String> keywords,
  ) {
    int score = 0;

    for (final keyword in keywords) {
      if (_containsKeyword(text, keyword)) {
        // A phrase is more specific than a single word.
        score += keyword.contains(' ') ? 5 : 3;
      }
    }

    return score;
  }

  bool _containsKeyword(
    String text,
    String keyword,
  ) {
    final normalizedKeyword = _normalize(keyword);

    if (normalizedKeyword.isEmpty) {
      return false;
    }

    final escaped = RegExp.escape(normalizedKeyword);

    final expression = RegExp(
      r'(^|\s)' + escaped + r'($|\s)',
    );

    return expression.hasMatch(text);
  }

  Map<String, int> _singleWordMatches(
    Set<String> tokens,
  ) {
    final scores = <String, int>{};

    for (final token in tokens) {
      final specializations = _wordAliases[token];

      if (specializations == null) {
        continue;
      }

      for (final specialization in specializations) {
        scores[specialization] = (scores[specialization] ?? 0) + 4;
      }
    }

    return scores;
  }

  String _normalize(String value) {
    return value
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9\s]'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  // ============================================================
  // BULK SINGLE-WORD ALIASES
  // ============================================================

  static const Map<String, List<String>> _wordAliases = {
    // General Physician
    'fever': ['General Physician'],
    'fevers': ['General Physician'],
    'chills': ['General Physician'],
    'chill': ['General Physician'],
    'fatigue': ['General Physician'],
    'tired': ['General Physician'],
    'tiredness': ['General Physician'],
    'weakness': ['General Physician'],
    'malaise': ['General Physician'],
    'cold': ['General Physician'],
    'flu': ['General Physician'],
    'dehydration': ['General Physician'],
    'thirst': ['General Physician'],
    'sweating': ['General Physician'],
    'shivering': ['General Physician'],
    'appetite': ['General Physician'],
    'exhaustion': ['General Physician'],
    'sluggishness': ['General Physician'],

    // Cardiologist
    'heart': ['Cardiologist'],
    'cardiac': ['Cardiologist'],
    'heartbeat': ['Cardiologist'],
    'palpitation': ['Cardiologist'],
    'palpitations': ['Cardiologist'],
    'pulse': ['Cardiologist'],
    'hypertension': ['Cardiologist'],
    'hypotension': ['Cardiologist'],
    'bloodpressure': ['Cardiologist'],
    'chest': ['Cardiologist'],
    'angina': ['Cardiologist'],
    'circulation': ['Cardiologist'],

    // Neurologist
    'headache': ['Neurologist'],
    'headaches': ['Neurologist'],
    'migraine': ['Neurologist'],
    'migraines': ['Neurologist'],
    'vertigo': ['Neurologist'],
    'tremor': ['Neurologist'],
    'tremors': ['Neurologist'],
    'numbness': ['Neurologist'],
    'tingling': ['Neurologist'],
    'seizure': ['Neurologist'],
    'seizures': ['Neurologist'],
    'convulsion': ['Neurologist'],
    'memory': ['Neurologist'],
    'confusion': ['Neurologist'],
    'blackout': ['Neurologist'],
    'coordination': ['Neurologist'],
    'neuropathy': ['Neurologist'],
    'nerve': ['Neurologist'],

    // Dermatologist
    'skin': ['Dermatologist'],
    'rash': ['Dermatologist'],
    'rashes': ['Dermatologist'],
    'itching': ['Dermatologist'],
    'itchy': ['Dermatologist'],
    'acne': ['Dermatologist'],
    'pimples': ['Dermatologist'],
    'eczema': ['Dermatologist'],
    'dermatitis': ['Dermatologist'],
    'hives': ['Dermatologist'],
    'dandruff': ['Dermatologist'],
    'scalp': ['Dermatologist'],
    'hairloss': ['Dermatologist'],
    'moles': ['Dermatologist'],
    'warts': ['Dermatologist'],
    'blisters': ['Dermatologist'],
    'pigmentation': ['Dermatologist'],

    // Dentist
    'tooth': ['Dentist'],
    'teeth': ['Dentist'],
    'toothache': ['Dentist'],
    'dental': ['Dentist'],
    'dentist': ['Dentist'],
    'gum': ['Dentist'],
    'gums': ['Dentist'],
    'cavity': ['Dentist'],
    'cavities': ['Dentist'],
    'molar': ['Dentist'],
    'molars': ['Dentist'],
    'wisdom': ['Dentist'],
    'braces': ['Dentist'],
    'tartar': ['Dentist'],
    'plaque': ['Dentist'],
    'abscess': ['Dentist'],
    'jaw': ['Dentist'],
    'cheek': ['Dentist'],
    'oral': ['Dentist'],
    'tongue': ['Dentist'],

    // Ophthalmologist
    'eye': ['Ophthalmologist'],
    'eyes': ['Ophthalmologist'],
    'vision': ['Ophthalmologist'],
    'eyesight': ['Ophthalmologist'],
    'blindness': ['Ophthalmologist'],
    'blurred': ['Ophthalmologist'],
    'floaters': ['Ophthalmologist'],
    'glaucoma': ['Ophthalmologist'],
    'cataract': ['Ophthalmologist'],
    'cataracts': ['Ophthalmologist'],
    'eyelid': ['Ophthalmologist'],
    'eyelids': ['Ophthalmologist'],
    'tearing': ['Ophthalmologist'],
    'watery': ['Ophthalmologist'],
    'photophobia': ['Ophthalmologist'],

    // Gastroenterologist
    'stomach': ['Gastroenterologist'],
    'abdominal': ['Gastroenterologist'],
    'abdomen': ['Gastroenterologist'],
    'bloating': ['Gastroenterologist'],
    'gas': ['Gastroenterologist'],
    'acidity': ['Gastroenterologist'],
    'heartburn': ['Gastroenterologist'],
    'reflux': ['Gastroenterologist'],
    'indigestion': ['Gastroenterologist'],
    'nausea': ['Gastroenterologist'],
    'vomiting': ['Gastroenterologist'],
    'diarrhea': ['Gastroenterologist'],
    'constipation': ['Gastroenterologist'],
    'stool': ['Gastroenterologist'],
    'bowel': ['Gastroenterologist'],
    'intestinal': ['Gastroenterologist'],
    'hiccups': ['Gastroenterologist'],
    'burping': ['Gastroenterologist'],

    // Orthopedic
    'bone': ['Orthopedic'],
    'bones': ['Orthopedic'],
    'joint': ['Orthopedic'],
    'joints': ['Orthopedic'],
    'knee': ['Orthopedic'],
    'knees': ['Orthopedic'],
    'back': ['Orthopedic'],
    'shoulder': ['Orthopedic'],
    'elbow': ['Orthopedic'],
    'wrist': ['Orthopedic'],
    'hip': ['Orthopedic'],
    'ankle': ['Orthopedic'],
    'foot': ['Orthopedic'],
    'heel': ['Orthopedic'],
    'fracture': ['Orthopedic'],
    'sprain': ['Orthopedic'],
    'ligament': ['Orthopedic'],
    'tendon': ['Orthopedic'],
    'muscle': ['Orthopedic'],
    'stiffness': ['Orthopedic'],
    'dislocation': ['Orthopedic'],

    // Pulmonologist
    'cough': ['Pulmonologist'],
    'coughing': ['Pulmonologist'],
    'wheezing': ['Pulmonologist'],
    'wheeze': ['Pulmonologist'],
    'phlegm': ['Pulmonologist'],
    'mucus': ['Pulmonologist'],
    'breathing': ['Pulmonologist'],
    'breathlessness': ['Pulmonologist'],
    'breathless': ['Pulmonologist'],
    'respiratory': ['Pulmonologist'],
    'asthma': ['Pulmonologist'],
    'sputum': ['Pulmonologist'],
    'congestion': ['Pulmonologist'],

    // ENT Specialist
    'ear': ['ENT Specialist'],
    'ears': ['ENT Specialist'],
    'earache': ['ENT Specialist'],
    'hearing': ['ENT Specialist'],
    'tinnitus': ['ENT Specialist'],
    'nose': ['ENT Specialist'],
    'nasal': ['ENT Specialist'],
    'sinus': ['ENT Specialist'],
    'sinusitis': ['ENT Specialist'],
    'throat': ['ENT Specialist'],
    'tonsil': ['ENT Specialist'],
    'tonsils': ['ENT Specialist'],
    'hoarse': ['ENT Specialist'],
    'hoarseness': ['ENT Specialist'],
    'snoring': ['ENT Specialist'],
    'smell': ['ENT Specialist'],
    'taste': ['ENT Specialist'],
    'nosebleed': ['ENT Specialist'],

    // Urologist
    'urine': ['Urologist'],
    'urinary': ['Urologist'],
    'urination': ['Urologist'],
    'bladder': ['Urologist'],
    'kidney': ['Urologist'],
    'kidneys': ['Urologist'],
    'flank': ['Urologist'],
    'groin': ['Urologist'],
    'testicle': ['Urologist'],
    'testicular': ['Urologist'],
    'scrotal': ['Urologist'],
    'penile': ['Urologist'],
    'prostate': ['Urologist'],
    'catheter': ['Urologist'],

    // Gynecologist
    'period': ['Gynecologist'],
    'periods': ['Gynecologist'],
    'menstrual': ['Gynecologist'],
    'menstruation': ['Gynecologist'],
    'ovulation': ['Gynecologist'],
    'pregnancy': ['Gynecologist'],
    'pregnant': ['Gynecologist'],
    'vaginal': ['Gynecologist'],
    'pelvic': ['Gynecologist'],
    'fertility': ['Gynecologist'],
    'miscarriage': ['Gynecologist'],
    'postpartum': ['Gynecologist'],
    'menopause': ['Gynecologist'],
    'breast': ['Gynecologist'],
    'nipple': ['Gynecologist'],

    // Pediatrician
    'child': ['Pediatrician'],
    'children': ['Pediatrician'],
    'kid': ['Pediatrician'],
    'kids': ['Pediatrician'],
    'baby': ['Pediatrician'],
    'babies': ['Pediatrician'],
    'infant': ['Pediatrician'],
    'infants': ['Pediatrician'],
    'newborn': ['Pediatrician'],
    'toddler': ['Pediatrician'],
    'pediatric': ['Pediatrician'],
    'paediatric': ['Pediatrician'],
    'feeding': ['Pediatrician'],
    'development': ['Pediatrician'],

    // Psychiatrist
    'anxiety': ['Psychiatrist'],
    'anxious': ['Psychiatrist'],
    'panic': ['Psychiatrist'],
    'depression': ['Psychiatrist'],
    'depressed': ['Psychiatrist'],
    'sadness': ['Psychiatrist'],
    'stress': ['Psychiatrist'],
    'worry': ['Psychiatrist'],
    'worries': ['Psychiatrist'],
    'overthinking': ['Psychiatrist'],
    'nervousness': ['Psychiatrist'],
    'insomnia': ['Psychiatrist'],
    'mood': ['Psychiatrist'],
    'trauma': ['Psychiatrist'],
    'phobia': ['Psychiatrist'],
  };

  // ============================================================
  // SYMPTOM DATABASE
  // ============================================================
  // Existing detailed symptom phrase database.

  static const Map<String, List<String>> symptomKeywords = {
    // ==========================================================
    // GENERAL PHYSICIAN
    // ==========================================================

    'General Physician': [
      'fever',
      'mild fever',
      'high fever',
      'chills',
      'body pain',
      'body ache',
      'fatigue',
      'tiredness',
      'weakness',
      'general weakness',
      'feeling unwell',
      'malaise',
      'loss of appetite',
      'increased appetite',
      'sudden weight loss',
      'unexplained weight gain',
      'dehydration',
      'excessive thirst',
      'excessive sweating',
      'night sweats',
      'cold sensation',
      'feeling hot',
      'shivering',
      'dizziness',
      'lightheadedness',
      'fainting',
      'feeling faint',
      'head discomfort',
      'general pain',
      'chronic pain',
      'sudden pain',
      'persistent pain',
      'swelling',
      'general swelling',
      'water retention',
      'difficulty sleeping',
      'insomnia',
      'excessive sleepiness',
      'daytime sleepiness',
      'restlessness',
      'irritability',
      'difficulty concentrating',
      'poor concentration',
      'loss of energy',
      'low energy',
      'feeling exhausted',
      'exercise intolerance',
      'reduced stamina',
      'feeling weak after exercise',
      'loss of strength',
      'appetite changes',
      'taste changes',
      'smell changes',
      'feeling cold frequently',
      'feeling hot frequently',
      'sudden tiredness',
      'persistent tiredness',
      'morning fatigue',
      'afternoon fatigue',
      'general discomfort',
      'malaise after meals',
      'malaise after exercise',
      'feeling shaky',
      'trembling',
      'unusual sweating',
      'cold sweats',
      'hot flashes',
      'feeling sleepy',
      'difficulty waking up',
      'poor sleep',
      'frequent waking',
      'restless sleep',
      'reduced activity tolerance',
      'reduced physical endurance',
      'feeling sluggish',
      'lack of energy',
      'loss of motivation',
      'feeling drained',
      'weakness after illness',
      'fatigue after activity',
      'persistent malaise',
      'general heaviness',
      'feeling uncomfortable',
      'feeling unusually tired',
      'sudden weakness',
      'persistent weakness',
      'reduced appetite',
      'increased thirst',
      'changes in appetite',
      'unexplained fatigue',
      'unexplained weakness',
      'unexplained swelling',
      'unexplained weight loss',
      'unexplained weight gain',
      'recurrent fever',
      'recurrent chills',
      'recurrent sweating',
      'persistent discomfort',
      'feeling sick',
      'cold',
      'flu',
      'mild fever',
    ],

    // ==========================================================
    // CARDIOLOGIST
    // ==========================================================

    'Cardiologist': [
      'chest pain',
      'chest pressure',
      'chest tightness',
      'chest heaviness',
      'heart pain',
      'heart discomfort',
      'palpitations',
      'fast heartbeat',
      'slow heartbeat',
      'irregular heartbeat',
      'racing heartbeat',
      'pounding heartbeat',
      'skipped heartbeat',
      'fluttering heartbeat',
      'shortness of breath',
      'breathlessness',
      'breathing difficulty',
      'difficulty breathing during exercise',
      'breathlessness while walking',
      'breathlessness while climbing stairs',
      'breathlessness while lying down',
      'sudden breathlessness',
      'swollen ankles',
      'swollen feet',
      'leg swelling',
      'foot swelling',
      'hand swelling',
      'facial swelling',
      'high blood pressure',
      'low blood pressure',
      'blood pressure fluctuations',
      'dizziness with standing',
      'fainting during exercise',
      'fainting episodes',
      'near fainting',
      'cold hands',
      'cold feet',
      'bluish lips',
      'bluish fingers',
      'reduced exercise tolerance',
      'fatigue during exercise',
      'chest discomfort after exercise',
      'chest pain while walking',
      'chest tightness during exercise',
      'heart racing',
      'heart fluttering',
      'heart pounding',
      'irregular pulse',
      'weak pulse',
      'rapid pulse',
      'slow pulse',
      'leg heaviness',
      'leg discomfort while walking',
      'calf pain while walking',
      'calf cramping while walking',
      'poor circulation sensation',
      'cold feet sensation',
      'chest burning',
      'chest fullness',
      'chest pressure after exertion',
      'breathlessness at night',
      'waking up breathless',
      'difficulty lying flat',
      'sudden heartbeat increase',
      'sudden heartbeat decrease',
      'persistent palpitations',
      'exercise related palpitations',
      'dizziness with palpitations',
      'weakness with palpitations',
      'chest pain with exertion',
      'chest discomfort with exertion',
      'chest heaviness after activity',
      'unusual fatigue with activity',
      'swelling of both legs',
      'swelling around ankles',
      'swelling after standing',
      'swelling after walking',
      'breathlessness with mild activity',
      'reduced walking tolerance',
      'reduced exercise capacity',
    ],

    // ==========================================================
    // NEUROLOGIST
    // ==========================================================

    'Neurologist': [
      'headache',
      'severe headache',
      'migraine',
      'migraine headache',
      'tension headache',
      'cluster headache',
      'head pressure',
      'head heaviness',
      'throbbing headache',
      'pulsating headache',
      'one sided headache',
      'headache behind eyes',
      'morning headache',
      'recurrent headache',
      'persistent headache',
      'sudden headache',
      'dizziness',
      'vertigo',
      'room spinning',
      'balance problems',
      'loss of balance',
      'unsteady walking',
      'difficulty walking',
      'tremor',
      'hand tremor',
      'leg tremor',
      'muscle twitching',
      'muscle spasms',
      'numbness',
      'tingling',
      'pins and needles',
      'burning sensation',
      'nerve pain',
      'shooting pain',
      'electric shock sensation',
      'facial numbness',
      'facial weakness',
      'arm numbness',
      'leg numbness',
      'hand numbness',
      'foot numbness',
      'finger numbness',
      'toe numbness',
      'arm weakness',
      'leg weakness',
      'hand weakness',
      'foot weakness',
      'muscle weakness',
      'sudden weakness',
      'one sided weakness',
      'difficulty speaking',
      'slurred speech',
      'speech difficulty',
      'word finding difficulty',
      'memory loss',
      'forgetfulness',
      'confusion',
      'difficulty concentrating',
      'seizure',
      'seizure like episode',
      'convulsions',
      'loss of consciousness',
      'fainting',
      'blackout episodes',
      'sleep disturbances',
      'excessive daytime sleepiness',
      'sleep attacks',
      'difficulty coordinating movements',
      'poor coordination',
      'hand coordination problems',
      'walking coordination problems',
      'facial twitching',
      'eye twitching',
      'muscle stiffness',
      'limb stiffness',
      'neck stiffness',
      'spasticity',
      'difficulty swallowing',
      'choking while eating',
      'voice changes',
      'difficulty controlling movements',
      'involuntary movements',
      'jerking movements',
      'muscle jerks',
      'restless legs',
      'burning feet',
      'chronic nerve pain',
      'back nerve pain',
      'sciatic pain',
      'shooting leg pain',
      'shooting arm pain',
      'neck nerve pain',
      'facial pain',
      'facial tingling',
      'ear related dizziness',
      'light sensitivity',
      'sound sensitivity',
      'visual aura',
      'migraine aura',
      'loss of sensation',
    ],

    // ==========================================================
    // DERMATOLOGIST
    // ==========================================================

    'Dermatologist': [
      'skin rash',
      'red rash',
      'itchy rash',
      'skin itching',
      'severe itching',
      'dry skin',
      'very dry skin',
      'oily skin',
      'acne',
      'pimples',
      'blackheads',
      'whiteheads',
      'acne scars',
      'skin allergy',
      'allergic rash',
      'skin irritation',
      'skin redness',
      'skin swelling',
      'skin peeling',
      'flaky skin',
      'eczema',
      'dermatitis',
      'contact dermatitis',
      'hives',
      'skin bumps',
      'small red bumps',
      'skin blisters',
      'fluid filled blisters',
      'skin sores',
      'skin ulcers',
      'non healing skin wound',
      'skin infection',
      'fungal skin infection',
      'ringworm',
      'athletes foot',
      'nail fungus',
      'scalp itching',
      'dandruff',
      'severe dandruff',
      'hair loss',
      'sudden hair loss',
      'patchy hair loss',
      'excessive hair shedding',
      'brittle hair',
      'scalp rash',
      'scalp redness',
      'scalp scaling',
      'skin discoloration',
      'dark skin patches',
      'light skin patches',
      'white skin patches',
      'hyperpigmentation',
      'skin darkening',
      'skin lightening',
      'moles',
      'changing mole',
      'skin growth',
      'skin lump',
      'warts',
      'skin tags',
      'excessive sweating',
      'sweaty palms',
      'sweaty feet',
      'cracked skin',
      'cracked heels',
      'cracked hands',
      'lip dryness',
      'lip cracking',
      'facial redness',
      'facial swelling',
      'facial rash',
      'itchy scalp',
      'itchy ears',
      'itchy hands',
      'itchy feet',
      'itchy legs',
      'itchy arms',
      'burning skin',
      'sensitive skin',
      'painful skin',
    ],

    // ==========================================================
    // DENTIST
    // ==========================================================

    'Dentist': [
      'tooth pain',
      'teeth pain',
      'toothache',
      'teeth ache',
      'dental pain',
      'gum pain',
      'swollen gums',
      'bleeding gums',
      'red gums',
      'sensitive teeth',
      'tooth sensitivity',
      'cavity',
      'tooth decay',
      'broken tooth',
      'cracked tooth',
      'loose tooth',
      'missing tooth',
      'wisdom tooth pain',
      'wisdom teeth pain',
      'wisdom tooth swelling',
      'jaw pain',
      'jaw swelling',
      'jaw stiffness',
      'difficulty chewing',
      'pain while chewing',
      'pain while biting',
      'gum swelling',
      'gum infection',
      'gum bleeding',
      'bad breath',
      'persistent bad breath',
      'mouth ulcer',
      'mouth sores',
      'tongue pain',
      'tongue swelling',
      'tongue sores',
      'tongue discoloration',
      'dry mouth',
      'excessive saliva',
      'difficulty opening mouth',
      'facial dental swelling',
      'tooth discoloration',
      'yellow teeth',
      'broken filling',
      'lost filling',
      'dental abscess',
      'pus near tooth',
      'tooth infection',
      'receding gums',
      'sensitive gums',
      'painful gums',
      'bleeding after brushing',
      'pain after dental treatment',
      'pain after tooth extraction',
      'swelling after extraction',
      'difficulty swallowing due to dental pain',
      'cheek swelling',
      'mouth bleeding',
      'oral pain',
      'mouth dryness',
      'burning mouth',
      'bad taste in mouth',
      'metallic taste in mouth',
      'difficulty biting',
      'tooth fracture',
      'tooth looseness',
      'dental plaque',
      'excessive tartar',
      'gum recession',
    ],

    // ==========================================================
    // OPHTHALMOLOGIST
    // ==========================================================

    'Ophthalmologist': [
      'eye pain',
      'eye redness',
      'red eyes',
      'blurred vision',
      'poor vision',
      'reduced vision',
      'double vision',
      'loss of vision',
      'partial vision loss',
      'sudden vision changes',
      'eye itching',
      'itchy eyes',
      'watery eyes',
      'dry eyes',
      'burning eyes',
      'eye irritation',
      'eye swelling',
      'eyelid swelling',
      'eye discharge',
      'sticky eyes',
      'eye infection',
      'eye strain',
      'tired eyes',
      'eye fatigue',
      'light sensitivity',
      'difficulty seeing at night',
      'night vision problems',
      'floaters',
      'flashes of light',
      'spots in vision',
      'shadow in vision',
      'eye pressure sensation',
      'pain behind eye',
      'headache around eyes',
      'difficulty focusing',
      'trouble reading',
      'watery vision',
      'excessive blinking',
      'eyelid twitching',
      'drooping eyelid',
      'unequal pupils',
      'eye trauma',
      'foreign body in eye',
      'dust in eye',
      'chemical irritation in eye',
      'red eyelids',
      'crusty eyelids',
      'eyelid pain',
      'eyelid lump',
      'stye',
      'recurrent stye',
      'eye dryness at night',
      'eye dryness while using screens',
      'blinking discomfort',
      'contact lens discomfort',
      'contact lens irritation',
      'eye watering in sunlight',
      'difficulty seeing colors',
      'color vision problems',
      'visual aura',
      'peripheral vision problems',
      'tunnel vision',
      'difficulty focusing on near objects',
      'difficulty focusing on distant objects',
      'eye heaviness',
      'eye pressure',
      'eye discomfort',
      'vision fluctuation',
      'temporary blurred vision',
      'eye pain with light',
    ],

    // ==========================================================
    // GASTROENTEROLOGIST
    // ==========================================================

    'Gastroenterologist': [
      'stomach pain',
      'abdominal pain',
      'stomach ache',
      'lower abdominal pain',
      'upper abdominal pain',
      'right abdominal pain',
      'left abdominal pain',
      'bloating',
      'gas',
      'excessive gas',
      'acidity',
      'heartburn',
      'acid reflux',
      'indigestion',
      'nausea',
      'vomiting',
      'frequent vomiting',
      'diarrhea',
      'loose stools',
      'constipation',
      'hard stools',
      'blood in stool',
      'black stool',
      'mucus in stool',
      'abdominal cramps',
      'stomach cramps',
      'intestinal cramps',
      'loss of appetite',
      'early fullness',
      'feeling full quickly',
      'difficulty swallowing',
      'painful swallowing',
      'food getting stuck',
      'excessive burping',
      'frequent belching',
      'excessive hiccups',
      'persistent hiccups',
      'burning stomach',
      'stomach heaviness',
      'abdominal fullness',
      'abdominal swelling',
      'recurrent abdominal pain',
      'chronic abdominal pain',
      'morning nausea',
      'nausea after eating',
      'vomiting after eating',
      'stomach pain after eating',
      'diarrhea after eating',
      'constipation after eating',
      'urgency to pass stool',
      'frequent bowel movements',
      'incomplete bowel movement',
      'pain during bowel movement',
      'anal discomfort',
      'rectal pain',
      'rectal bleeding',
      'vomiting blood',
      'persistent indigestion',
      'food intolerance symptoms',
      'food related bloating',
      'food related abdominal pain',
      'chronic diarrhea',
      'chronic constipation',
      'alternating constipation and diarrhea',
      'excessive abdominal gas',
      'abdominal tenderness',
      'abdominal discomfort',
      'upper stomach burning',
      'sour taste in mouth',
      'acid taste in mouth',
      'reflux at night',
      'reflux after meals',
      'difficulty passing stool',
      'painful bowel movement',
      'sudden bowel changes',
      'change in stool color',
      'change in stool frequency',
      'persistent nausea',
      'persistent vomiting',
      'persistent bloating',
    ],

    // ==========================================================
    // ORTHOPEDIC
    // ==========================================================

    'Orthopedic': [
      'back pain',
      'lower back pain',
      'upper back pain',
      'middle back pain',
      'neck pain',
      'shoulder pain',
      'shoulder stiffness',
      'shoulder weakness',
      'arm pain',
      'elbow pain',
      'wrist pain',
      'hand pain',
      'finger pain',
      'hip pain',
      'knee pain',
      'knee stiffness',
      'knee swelling',
      'ankle pain',
      'foot pain',
      'heel pain',
      'toe pain',
      'joint pain',
      'bone pain',
      'muscle pain',
      'muscle stiffness',
      'muscle weakness',
      'joint stiffness',
      'joint swelling',
      'joint tenderness',
      'difficulty walking',
      'difficulty standing',
      'difficulty climbing stairs',
      'pain while walking',
      'pain while running',
      'pain while bending',
      'pain while lifting',
      'pain while sitting',
      'pain while standing',
      'pain after exercise',
      'sports injury',
      'muscle strain',
      'ligament injury',
      'tendon pain',
      'tendon swelling',
      'sprain',
      'fracture',
      'suspected fracture',
      'bone injury',
      'joint injury',
      'dislocation',
      'shoulder dislocation',
      'knee injury',
      'ankle injury',
      'wrist injury',
      'elbow injury',
      'back injury',
      'neck injury',
      'repetitive strain',
      'joint clicking',
      'joint popping',
      'knee clicking',
      'shoulder clicking',
      'hip clicking',
      'stiff neck',
      'frozen shoulder',
      'knee instability',
      'ankle instability',
      'weak knees',
      'weak ankles',
      'muscle cramps',
      'leg cramps',
      'calf cramps',
      'foot cramps',
      'hamstring pain',
      'shin pain',
      'achilles pain',
      'plantar heel pain',
      'sciatic pain',
      'shooting back pain',
      'chronic joint pain',
    ],

    // ==========================================================
    // PULMONOLOGIST
    // ==========================================================

    'Pulmonologist': [
      'cough',
      'dry cough',
      'wet cough',
      'persistent cough',
      'chronic cough',
      'severe cough',
      'cough with mucus',
      'cough with phlegm',
      'bloody cough',
      'shortness of breath',
      'breathlessness',
      'difficulty breathing',
      'wheezing',
      'chest congestion',
      'chest tightness',
      'chest discomfort while breathing',
      'pain while breathing',
      'rapid breathing',
      'noisy breathing',
      'difficulty taking deep breaths',
      'breathing difficulty at night',
      'breathlessness while walking',
      'breathlessness while exercising',
      'breathlessness while climbing stairs',
      'breathlessness while sleeping',
      'waking up breathless',
      'sore throat',
      'scratchy throat',
      'throat irritation',
      'runny nose',
      'blocked nose',
      'nasal congestion',
      'sneezing',
      'frequent sneezing',
      'postnasal drip',
      'mucus in throat',
      'hoarse voice',
      'voice loss',
      'excess phlegm',
      'green phlegm',
      'yellow phlegm',
      'clear phlegm',
      'difficulty clearing mucus',
      'recurrent respiratory infections',
      'recurrent cough',
      'night cough',
      'morning cough',
      'exercise induced cough',
      'cold related cough',
      'breathing noise',
      'whistling breathing',
      'chest rattling',
      'throat congestion',
      'nasal discharge',
      'sinus congestion',
      'sinus pressure',
      'facial sinus pain',
      'difficulty breathing through nose',
      'persistent nasal blockage',
      'frequent throat clearing',
      'choking sensation',
      'breathing discomfort',
      'reduced breathing capacity',
      'reduced exercise breathing tolerance',
      'chest heaviness',
      'breathing difficulty during sleep',
      'persistent wheezing',
      'persistent breathlessness',
      'persistent respiratory discomfort',
    ],

    // ==========================================================
    // ENT SPECIALIST
    // ==========================================================

    'ENT Specialist': [
      'ear pain',
      'earache',
      'ear blockage',
      'ear fullness',
      'ringing in ears',
      'tinnitus',
      'hearing loss',
      'reduced hearing',
      'sudden hearing loss',
      'ear discharge',
      'ear itching',
      'ear infection',
      'dizziness from ear',
      'balance problems',
      'nose pain',
      'nose blockage',
      'nasal congestion',
      'runny nose',
      'nose bleeding',
      'frequent nosebleeds',
      'sneezing',
      'sinus pain',
      'sinus pressure',
      'facial pressure',
      'facial pain',
      'loss of smell',
      'reduced sense of smell',
      'altered smell',
      'loss of taste',
      'reduced taste',
      'sore throat',
      'throat pain',
      'difficulty swallowing',
      'painful swallowing',
      'tonsil swelling',
      'enlarged tonsils',
      'tonsil pain',
      'bad breath',
      'hoarse voice',
      'voice change',
      'voice loss',
      'persistent throat clearing',
      'mucus in throat',
      'postnasal drip',
      'snoring',
      'loud snoring',
      'sleep breathing problems',
      'foreign body in ear',
      'ear wax blockage',
      'excessive ear wax',
      'ear pressure',
      'ear popping',
      'ear sensitivity',
      'sound sensitivity',
      'throat irritation',
      'throat dryness',
      'nasal dryness',
      'nasal irritation',
      'nasal discharge',
      'recurrent sinus problems',
      'chronic sinus pressure',
      'difficulty breathing through nose',
      'enlarged lymph nodes in neck',
      'neck throat swelling',
      'swollen glands',
      'ear ringing after noise',
      'hearing difficulty in crowds',
      'difficulty understanding speech',
      'persistent hoarseness',
    ],

    // ==========================================================
    // UROLOGIST
    // ==========================================================

    'Urologist': [
      'painful urination',
      'burning urination',
      'frequent urination',
      'urgent urination',
      'difficulty urinating',
      'weak urine stream',
      'interrupted urine stream',
      'blood in urine',
      'cloudy urine',
      'dark urine',
      'foul smelling urine',
      'urine leakage',
      'urinary incontinence',
      'bedwetting',
      'incomplete bladder emptying',
      'lower abdominal pain',
      'pelvic pain',
      'kidney pain',
      'flank pain',
      'side pain',
      'back pain with urination',
      'kidney stone pain',
      'groin pain',
      'frequent nighttime urination',
      'excessive nighttime urination',
      'reduced urine output',
      'increased urine output',
      'sudden urine changes',
      'urinary urgency',
      'urinary frequency',
      'urinary retention',
      'difficulty starting urination',
      'dribbling urine',
      'urine leakage while coughing',
      'urine leakage while sneezing',
      'pain after urination',
      'pelvic pressure',
      'bladder discomfort',
      'bladder pain',
      'recurrent urinary symptoms',
      'recurrent urinary infection symptoms',
      'fever with urinary symptoms',
      'chills with urinary symptoms',
      'blood clots in urine',
      'foamy urine',
      'persistent foamy urine',
      'change in urine color',
      'change in urine smell',
      'frequent urination at night',
      'pain near kidneys',
      'sharp flank pain',
      'cramping flank pain',
      'groin discomfort',
      'testicular pain',
      'testicular swelling',
      'scrotal swelling',
      'scrotal pain',
      'penile pain',
      'penile swelling',
      'urinary discomfort',
    ],

    // ==========================================================
    // GYNECOLOGIST
    // ==========================================================

    'Gynecologist': [
      'pelvic pain',
      'lower abdominal pain',
      'menstrual pain',
      'painful periods',
      'heavy periods',
      'irregular periods',
      'missed periods',
      'frequent periods',
      'prolonged periods',
      'spotting',
      'bleeding between periods',
      'bleeding after intercourse',
      'vaginal bleeding',
      'vaginal discharge',
      'abnormal discharge',
      'vaginal itching',
      'vaginal burning',
      'vaginal dryness',
      'pelvic pressure',
      'pain during intercourse',
      'painful intercourse',
      'breast pain',
      'breast tenderness',
      'breast lump',
      'breast swelling',
      'nipple discharge',
      'nipple pain',
      'menopause symptoms',
      'hot flashes',
      'night sweats',
      'mood changes around periods',
      'premenstrual symptoms',
      'severe premenstrual symptoms',
      'fertility concerns',
      'difficulty conceiving',
      'pregnancy related discomfort',
      'morning nausea during pregnancy',
      'pregnancy vomiting',
      'pregnancy pelvic pain',
      'pregnancy back pain',
      'pregnancy swelling',
      'postpartum pain',
      'postpartum bleeding',
      'postpartum fatigue',
      'menstrual bloating',
      'menstrual headache',
      'menstrual breast tenderness',
      'menstrual back pain',
      'vaginal odor',
      'pelvic discomfort',
      'cervical discomfort',
      'recurrent vaginal symptoms',
      'abnormal menstrual flow',
      'very painful periods',
      'very heavy menstrual bleeding',
      'sudden menstrual changes',
      'breast skin changes',
      'nipple skin changes',
      'pelvic cramps',
      'ovulation pain',
      'vaginal irritation',
      'vaginal soreness',
      'hormonal symptoms',
      'perimenopause symptoms',
      'menopause related dryness',
      'menopause related sleep problems',
      'menopause related hot flashes',
      'womens reproductive health concerns',
    ],

    // ==========================================================
    // PEDIATRICIAN
    // ==========================================================

    'Pediatrician': [
      'child fever',
      'child cough',
      'child cold',
      'child vomiting',
      'child diarrhea',
      'child stomach pain',
      'child constipation',
      'child rash',
      'child skin itching',
      'child ear pain',
      'child sore throat',
      'child breathing difficulty',
      'child wheezing',
      'child poor appetite',
      'child weakness',
      'child excessive sleepiness',
      'child difficulty sleeping',
      'child headache',
      'child dizziness',
      'child fainting',
      'child seizure',
      'child developmental concern',
      'delayed speech',
      'delayed walking',
      'poor weight gain',
      'excessive weight gain',
      'child weight loss',
      'feeding difficulty',
      'difficulty swallowing in child',
      'recurrent infections',
      'child abdominal pain',
      'child joint pain',
      'child bone pain',
      'child urinary problems',
      'child bedwetting',
    ],

    // ==========================================================
    // PSYCHIATRIST
    // ==========================================================

    'Psychiatrist': [
      'anxiety',
      'excessive worry',
      'panic attacks',
      'panic symptoms',
      'persistent sadness',
      'low mood',
      'loss of interest',
      'loss of motivation',
      'irritability',
      'mood swings',
      'difficulty concentrating',
      'racing thoughts',
      'excessive thoughts',
      'intrusive thoughts',
      'repetitive thoughts',
      'sleep problems',
      'difficulty sleeping',
      'excessive sleeping',
      'stress',
      'work related stress',
      'academic stress',
      'emotional distress',
      'social anxiety',
      'fear of social situations',
      'fear of leaving home',
      'persistent nervousness',
      'feeling overwhelmed',
      'difficulty relaxing',
      'emotional exhaustion',
      'poor concentration due to stress',
      'memory difficulties associated with stress',
      'changes in appetite with stress',
      'sleep changes with stress',
      'persistent worry',
      'difficulty coping with daily activities',
    ],
  };
}
